services:
  sellhelp:
      image: sellhelp:latest
      ports:
        - 8080:8080
      depends_on:
        database:
          condition: service_healthy
        storage:
          condition: service_started
        bridge:
          condition: service_started
        nginx:
          condition: service_started
      env_file: '.env-docker'

  sellhelp-frontend:
    image: sellhelp-frontend
    ports:
      - 5173:5173
    depends_on:
     - sellhelp
     - database
     - storage
     - bridge
     - nginx
    env_file: '.env-docker'

  database:
      image: postgres:latest
      ports:
        - 5432:5432
      env_file: '.env-docker'
      volumes:
        - ./data:/docker-entrypoint-initdb.d
      healthcheck:
        test: ["CMD-SHELL", "psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1' || exit 1"]
        interval: 5s
        timeout: 5s
        retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - database


  storage:
    image: 'minio/minio:latest'
    ports:
      - 9000:9000
      - 9001:9001
    env_file: '.env-docker'
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - storage

  bridge:
    image: dancwilliams/protonmail-bridge
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - ./protonmail:/root
