FROM shenxn/protonmail-bridge:latest

# Create config folder
RUN mkdir -p /root/.config/protonmail

# Copy the entrypoint script into the image
COPY bridge-entrypoint.sh /bridge-entrypoint.sh
RUN chmod +x /bridge-entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/bridge-entrypoint.sh"]